// This file is auto-generated by @hey-api/openapi-ts

export { client, type CreateClientConfig } from './client.gen';
export { type Options, UmbracoCommunityLinkedPagesService } from './sdk.gen';
export type { ClientOptions, CreateLinkData, CreateLinkError, CreateLinkErrors, CreateLinkResponse, CreateLinkResponses, GetChildLinksData, GetChildLinksErrors, GetChildLinksResponse, GetChildLinksResponses, GetIgnoredTypeAliasData, GetIgnoredTypeAliasErrors, GetIgnoredTypeAliasResponse, GetIgnoredTypeAliasResponses, GetParentLinksData, GetParentLinksErrors, GetParentLinksResponse, GetParentLinksResponses, LinkedPageInfo, ProblemDetails, RemoveLinkData, RemoveLinkError, RemoveLinkErrors, RemoveLinkResponse, RemoveLinkResponses } from './types.gen';
