// This file is auto-generated by @hey-api/openapi-ts

export { deleteRemoveLink, getChildLinks, getIgnoredTypeAlias, getParentLinks, type Options, postCreateLink } from './sdk.gen';
export type { ClientOptions, DeleteRemoveLinkData, DeleteRemoveLinkError, DeleteRemoveLinkErrors, DeleteRemoveLinkResponse, DeleteRemoveLinkResponses, GetChildLinksData, GetChildLinksErrors, GetChildLinksResponse, GetChildLinksResponses, GetIgnoredTypeAliasData, GetIgnoredTypeAliasErrors, GetIgnoredTypeAliasResponse, GetIgnoredTypeAliasResponses, GetParentLinksData, GetParentLinksErrors, GetParentLinksResponse, GetParentLinksResponses, LinkedPageInfo, PostCreateLinkData, PostCreateLinkError, PostCreateLinkErrors, PostCreateLinkResponse, PostCreateLinkResponses, ProblemDetails } from './types.gen';
