// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateLinkData, CreateLinkErrors, CreateLinkResponses, GetChildLinksData, GetChildLinksErrors, GetChildLinksResponses, GetIgnoredTypeAliasData, GetIgnoredTypeAliasErrors, GetIgnoredTypeAliasResponses, GetParentLinksData, GetParentLinksErrors, GetParentLinksResponses, RemoveLinkData, RemoveLinkErrors, RemoveLinkResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbracoCommunityLinkedPagesService {
    public static createLink<ThrowOnError extends boolean = true>(options?: Options<CreateLinkData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateLinkResponses, CreateLinkErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/umbracocommunitylinkedpages/api/v1/CreateLink',
            ...options
        });
    }
    
    public static getChildLinks<ThrowOnError extends boolean = true>(options?: Options<GetChildLinksData, ThrowOnError>) {
        return (options?.client ?? client).get<GetChildLinksResponses, GetChildLinksErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/umbracocommunitylinkedpages/api/v1/GetChildLinks',
            ...options
        });
    }
    
    public static getIgnoredTypeAlias<ThrowOnError extends boolean = true>(options?: Options<GetIgnoredTypeAliasData, ThrowOnError>) {
        return (options?.client ?? client).get<GetIgnoredTypeAliasResponses, GetIgnoredTypeAliasErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/umbracocommunitylinkedpages/api/v1/GetIgnoredTypeAlias',
            ...options
        });
    }
    
    public static getParentLinks<ThrowOnError extends boolean = true>(options?: Options<GetParentLinksData, ThrowOnError>) {
        return (options?.client ?? client).post<GetParentLinksResponses, GetParentLinksErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/umbracocommunitylinkedpages/api/v1/GetParentLinks',
            ...options
        });
    }
    
    public static removeLink<ThrowOnError extends boolean = true>(options?: Options<RemoveLinkData, ThrowOnError>) {
        return (options?.client ?? client).delete<RemoveLinkResponses, RemoveLinkErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/umbracocommunitylinkedpages/api/v1/RemoveLink',
            ...options
        });
    }
}
