// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteRemoveLinkData, DeleteRemoveLinkErrors, DeleteRemoveLinkResponses, GetChildLinksData, GetChildLinksErrors, GetChildLinksResponses, GetIgnoredTypeAliasData, GetIgnoredTypeAliasErrors, GetIgnoredTypeAliasResponses, GetParentLinksData, GetParentLinksErrors, GetParentLinksResponses, PostCreateLinkData, PostCreateLinkErrors, PostCreateLinkResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getChildLinks = <ThrowOnError extends boolean = false>(options?: Options<GetChildLinksData, ThrowOnError>) => (options?.client ?? client).get<GetChildLinksResponses, GetChildLinksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/ChildLinks',
    ...options
});

export const postCreateLink = <ThrowOnError extends boolean = false>(options?: Options<PostCreateLinkData, ThrowOnError>) => (options?.client ?? client).post<PostCreateLinkResponses, PostCreateLinkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/CreateLink',
    ...options
});

export const getIgnoredTypeAlias = <ThrowOnError extends boolean = false>(options?: Options<GetIgnoredTypeAliasData, ThrowOnError>) => (options?.client ?? client).get<GetIgnoredTypeAliasResponses, GetIgnoredTypeAliasErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/IgnoredTypeAlias',
    ...options
});

export const getParentLinks = <ThrowOnError extends boolean = false>(options?: Options<GetParentLinksData, ThrowOnError>) => (options?.client ?? client).get<GetParentLinksResponses, GetParentLinksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/ParentLinks',
    ...options
});

export const deleteRemoveLink = <ThrowOnError extends boolean = false>(options?: Options<DeleteRemoveLinkData, ThrowOnError>) => (options?.client ?? client).delete<DeleteRemoveLinkResponses, DeleteRemoveLinkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/RemoveLink',
    ...options
});
