// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44372' | (string & {});
};

export type LinkedPageInfo = {
    relationId: number;
    pageId: number;
    name: string;
    path: string;
    relationTypeId: number;
    relationType: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type CreateLinkData = {
    body?: never;
    path?: never;
    query?: {
        parent?: string;
        child?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/CreateLink';
};

export type CreateLinkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateLinkError = CreateLinkErrors[keyof CreateLinkErrors];

export type CreateLinkResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type CreateLinkResponse = CreateLinkResponses[keyof CreateLinkResponses];

export type GetChildLinksData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/GetChildLinks';
};

export type GetChildLinksErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetChildLinksResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type GetChildLinksResponse = GetChildLinksResponses[keyof GetChildLinksResponses];

export type GetIgnoredTypeAliasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/GetIgnoredTypeAlias';
};

export type GetIgnoredTypeAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetIgnoredTypeAliasResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetIgnoredTypeAliasResponse = GetIgnoredTypeAliasResponses[keyof GetIgnoredTypeAliasResponses];

export type GetParentLinksData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/GetParentLinks';
};

export type GetParentLinksErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetParentLinksResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type GetParentLinksResponse = GetParentLinksResponses[keyof GetParentLinksResponses];

export type RemoveLinkData = {
    body?: never;
    path?: never;
    query?: {
        key?: number;
        currentPage?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/RemoveLink';
};

export type RemoveLinkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type RemoveLinkError = RemoveLinkErrors[keyof RemoveLinkErrors];

export type RemoveLinkResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type RemoveLinkResponse = RemoveLinkResponses[keyof RemoveLinkResponses];
