// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44317/' | (string & {});
};

export type LinkedPageInfo = {
    relationId: number | string;
    pageId: number | string;
    name: string;
    path: string;
    relationTypeId: number | string;
    relationType: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type GetChildLinksData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/ChildLinks';
};

export type GetChildLinksErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetChildLinksResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type GetChildLinksResponse = GetChildLinksResponses[keyof GetChildLinksResponses];

export type PostCreateLinkData = {
    body?: never;
    path?: never;
    query?: {
        parent?: string;
        child?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/CreateLink';
};

export type PostCreateLinkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostCreateLinkError = PostCreateLinkErrors[keyof PostCreateLinkErrors];

export type PostCreateLinkResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type PostCreateLinkResponse = PostCreateLinkResponses[keyof PostCreateLinkResponses];

export type GetIgnoredTypeAliasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/IgnoredTypeAlias';
};

export type GetIgnoredTypeAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetIgnoredTypeAliasResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetIgnoredTypeAliasResponse = GetIgnoredTypeAliasResponses[keyof GetIgnoredTypeAliasResponses];

export type GetParentLinksData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/ParentLinks';
};

export type GetParentLinksErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetParentLinksResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type GetParentLinksResponse = GetParentLinksResponses[keyof GetParentLinksResponses];

export type DeleteRemoveLinkData = {
    body?: never;
    path?: never;
    query?: {
        key?: number | string;
        currentPage?: string;
    };
    url: '/umbraco/umbracocommunitylinkedpages/api/v1/RemoveLink';
};

export type DeleteRemoveLinkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DeleteRemoveLinkError = DeleteRemoveLinkErrors[keyof DeleteRemoveLinkErrors];

export type DeleteRemoveLinkResponses = {
    /**
     * OK
     */
    200: Array<LinkedPageInfo>;
};

export type DeleteRemoveLinkResponse = DeleteRemoveLinkResponses[keyof DeleteRemoveLinkResponses];
