blank_issues_enabled: false
contact_links:
  - name: Discussion / Support
    url: https://our.umbraco.com/packages/backoffice-extensions/linked-pages/linked-pages-feedback/
    about: Please ask general questions and get support on the Umbraco community forum.
